name: Dryrun
on:
  push:
    paths:
      - ".github/workflows/dryrun.yml"
      - "apps/**"
      - "package.json"
  workflow_dispatch:

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn
      - name: Write .env
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .env
          contents: |
            DISCORD_BOT_TOKEN=test
            DISCORD_APP_ID=273518732733710337
            DEVELOPMENT_GUILD_ID=
            DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"
          write-mode: overwrite

      - name: Write apps/dashboard/.env
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: apps/dashboard/.env
          contents: |
            CLIENT_ID=999999999999999999
            CLIENT_SECRET=test

            PATREON_CLIENT_ID=test
            PATREON_CLIENT_SECRET=test

            PATRON_TIER_MAP={"00001":2,"0002":3}
            PATREON_WEBHOOK_SECRET=test

            GOOGLE_CLIENT_ID=test
            GOOGLE_CLIENT_SECRET=test

            MICROSOFT_CLIENT_ID=test
            MICROSOFT_CLIENT_SECRET=test

            APP_URI=http://localhost:3000
            JWT_SECRET=1234
          write-mode: overwrite

      - name: Build Bot
        run: cd apps/bot && yarn prisma:generate && yarn build

      - name: Build Dashboard
        run: cd apps/dashboard && yarn prisma:generate && yarn build

      - name: Build Download
        run: cd apps/download && yarn build

      - name: Build Tasks
        run: cd apps/tasks && yarn prisma:generate && yarn build
