name: Manypkg
on:
  push:
    paths:
      - ".github/workflows/lintrepo.yml"
      - "apps/*/package.json"
      - "package.json"
  workflow_dispatch:

jobs:
  check:
    name: Lint monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run Manypkg
        run: yarn lint:monorepo
